// GENERATED FILE - DO NOT EDIT
// ------------------------------------------------------------
// This file was generated by the FlutterFire CLI.
// ------------------------------------------------------------

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQoHE5vYxua4qsbJqdkRwpBLxMJMCYUZw',
    appId: '1:296873056136:android:ac0310f6b07dfdb0f74c3d',
    messagingSenderId: '296873056136',
    projectId: 'flag-pic-d497b',
    storageBucket: 'flag-pic-d497b.firebasestorage.app',
  );

  /// 🔹 Android

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWBoDJJVqPnZBCyA5fSiLD85_WV9lIJxI',
    appId: '1:296873056136:web:fb70b9f7d8529326f74c3d',
    messagingSenderId: '296873056136',
    projectId: 'flag-pic-d497b',
    authDomain: 'flag-pic-d497b.firebaseapp.com',
    storageBucket: 'flag-pic-d497b.firebasestorage.app',
  );

  /// 🔹 Web (ถ้าไม่ได้ใช้ Web สามารถปล่อยไว้ได้)

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoWcBP0wBpKQeR2bcmT7eogz2SxTByGqo',
    appId: '1:296873056136:ios:866d2153a60998e9f74c3d',
    messagingSenderId: '296873056136',
    projectId: 'flag-pic-d497b',
    storageBucket: 'flag-pic-d497b.firebasestorage.app',
    iosBundleId: 'com.example.suteePic',
  );

  /// 🔹 iOS (ใส่เมื่อใช้จริง)

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoWcBP0wBpKQeR2bcmT7eogz2SxTByGqo',
    appId: '1:296873056136:ios:866d2153a60998e9f74c3d',
    messagingSenderId: '296873056136',
    projectId: 'flag-pic-d497b',
    storageBucket: 'flag-pic-d497b.firebasestorage.app',
    iosBundleId: 'com.example.suteePic',
  );

  /// 🔹 macOS (ถ้าไม่ใช้ ปล่อยไว้)

  /// 🔹 Windows (ถ้าไม่ใช้ ปล่อยไว้)
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyXXXXXXXXXXXXXXX",
    appId: "1:755264578542:windows:xxxxxxxxxxxxxxxx",
    messagingSenderId: "755264578542",
    projectId: "sutee-flutter-demo",
    storageBucket: "sutee-flutter-demo.appspot.com",
  );
}